### ISSUE TITLE
Removing cloud provider dependencies to k8s.io/kubernetes

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#1]
Duplicating https://github.com/kubernetes/kubernetes/issues/69585 to track milestones more easily. 

As part of a long running initiative to remove cloud providers out of kubernetes/kubernetes, it's required to remove dependencies to kubernetes/kubernetes so we can place them into a staging directory. The following dependencies need to be removed from `k8s.io/kubernetes/pkg/cloudprovider/providers`:

Dependency checklist:
- [x] `pkg/api/legacyscheme`
- [x] `pkg/api/service` (@andrewsykim)
- [X] `pkg/api/v1/pod` (@andrewsykim)
- [x] `pkg/api/v1/service` (@andrewsykim)
- [X] `pkg/apis/apps` (@andrewsykim)
- [X] `pkg/apis/autoscaling` (@andrewsykim)
- [x] `pkg/apis/core` (@islinwb, @dims)
- [x] `pkg/apis/core/helper` (@islinwb, @dims)
- [X] `pkg/apis/core/install` (@andrewsykim)
- [X] `pkg/apis/core/pods` (@andrewsykim)
- [x] `pkg/apis/core/v1` (@islinwb, @dims)
- [x] `pkg/apis/core/v1/helper` (@islinwb, @andrewsykim)
- [X] `pkg/apis/core/validation` (@andrewsykim)
- [X] `pkg/apis/scheduling` (@andrewsykim)
- [X] `pkg/capabilities` (@andrewsykim)
- [X] `pkg/controller` (@stewart-yu)
- [x] `pkg/credentialprovider` (@mcrute)
- [x] `pkg/credentialprovider/aws` (@mcrute)
- [X] `pkg/cloudprovider` (@cheftako) 
- [x] `pkg/features` (@andrewsykim)
- [X] `pkg/fieldpath` (@andrewsykim)
- [x] `pkg/kubelet/apis` (@islinwb , @dims)
- [x] `pkg/version` (@andrewsykim) 
- [X] `pkg/kubelet/types`(@andrewsykim)
- [X] `pkg/master/ports` (@andrewsykim)
- [X] `pkg/security/apparmor`(@andrewsykim)
- [X] `pkg/serviceaccount` (@andrewsykim)
- [x] `pkg/util/keymutex` (@dims)
- [X] `pkg/util/hash` (@andrewsykim)
- [x] `pkg/util/file` (@mcrute) 
- [x] `pkg/util/net/sets` (@mcrute, @ashishranjan738)
- [x] `pkg/util/strings` (@dims)
- [X] `pkg/util/taints` (@stewart-yu)
- [x] `pkg/volume` (@islinwb, @andrewsykim)
- [x] `pkg/volume/util` (@islinwb, @andrewsykim)
- [x] `pkg/volume/util/fs` (@andrewsykim)
- [x] `pkg/volume/util/recyclerclient` (@andrewsykim)
- [x] `pkg/volume/util/types` (@andrewsykim)
- [x] `pkg/volume/util/volumepathhandler` (@andrewsykim)

**Comment by dims** [comment]
What's left here @andrewsykim ?

**Comment by andrewsykim** [comment]
@dims just `pkg/util/mount` but if there are no plans to move the in-tree openstack provider to staging we can close this out. You mentioned previously that there were no plans, can you confirm here?

**Comment by andrewsykim** [comment]
This is done given we're not staging any more cloud provdiers, let me know if anything changes with OpenStack @dims
