### ISSUE TITLE
Better cloud LB names

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#10]
LBs provisioned by Kubernetes on any cloud provider uses auto-generated names based on the Service's UUID (e.g. `a44e18e4c552b11e683bb02fff13e176`) which is not very human-friendly. With https://github.com/kubernetes/kubernetes/pull/66589 merged it should be doable to have each provider set LB names based on naming requirements. 

SIG CP tracking issue for https://github.com/kubernetes/kubernetes/issues/69293. 

This will need a KEP reviewed by SIG network & cloud-provider.

**Comment by rvillablanca** [comment]
Hi all, @andrewsykim there is a simple `TODO` here related with this issue

https://github.com/kubernetes/cloud-provider/blob/1bd40cdc05f920de6af55dad4abd709cf646dea1/fake/fake.go#L174

but for `fake` package. If I understand well this is for testing purposes only so I was thinking to improve this by using names like docker does for container names. Would this be friendlier? or the name should be generated from parameters only ?
