### ISSUE TITLE
Finalizer Protection for Service LoadBalancers

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#16]
This is mainly a SIG Cloud Provider tracking/backlog issue, more details on the problem here https://github.com/kubernetes/kubernetes/issues/53451

We have two (stale) PRs open to add finalizer protection support for cloud provider LBs:
https://github.com/kubernetes/kubernetes/pull/54569 
https://github.com/kubernetes/kubernetes/pull/65912 

We have users who have report issues that their cloud LBs are not being deleted when they delete the corresponding Service. Adding finalizer protection would ensure the Service resource is not fully deleted until the correlating LB is also deleted.

**Comment by bowei** [comment]
@jhorwit2: do you mind throwing together a small KEP referencing your PRs to make sure this is able to get out in the 1.15 timeframe? 
We now require KEPs for most changes, and this one seems to be a big enough behavior change to warrant it.
I can help out with the KEP part if it makes it easier...

**Comment by andrewsykim** [comment]
@jhorwit2 I'd like to bump this into p1 for v1.15, if you don't have cycles please let me know and we can find other folks in the SIG to work on it :).

**Comment by bowei** [comment]
@MrHohn has done a lot of the reviews for the two existing PRs and has cycles in 1.15 to help get this in...

**Comment by andrewsykim** [comment]
Thanks @bowei! @jiatongw and I have started some initial work on the KEP, any objections if we open the KEP in the next week or two and assign you and @MrHohn for review?

**Comment by bowei** [comment]
sgtm -- I put as an item on sig-net to ping if anyone else is interested.

**Comment by andrewsykim** [comment]
Sweet, I think once the KEP is in we can split the KEP into implementable pieces and delegate work from there

**Comment by jiatongw** [comment]
Sure @andrewsykim thanks

**Comment by andrewsykim** [comment]
Spoke with @bowei offline, I don't think we need more than 1 person working on this at once, makes more sense if @MrHohn takes this (KEP + implementation) for 1.15
