### ISSUE TITLE
Nodes are being registered multiple times in the cloud-controller-manager

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#18]
In some situations, the cloud-controller-manager tries to register the same node twice. I need to dig into this a bit more, but my guess is that we are receiving a 2nd update event on a node that is currently being registered. 

I think one reasonable solution to this is to store a map of nodes that are currently being registered and skip registration if that node exists in the map. Delete the entry in the map after the node is done registration so it can be registered again later if desired. 

Typically processing control loops twice is not an issue due to the idempotent nature of controllers, but node registration for a cloud provider can become pretty expensive so there may be some value in optimizing this. @tghartland has kindly left a detailed report of this in https://github.com/kubernetes/kubernetes/issues/75285.

**Comment by yastij** [comment]
@andrewsykim  - I agree, building a local cache on the controller side seems to be something we're already doing on others controllers. We might also want to merge add/update as it pretty much does the same thing, feel free to assign me if not working on it.

**Comment by nzoueidi** [comment]
I am digging into this, any hints would be very appreciated.

**Comment by tghartland** [comment]
@nzoueidi This is what I think is happening https://github.com/kubernetes/kubernetes/pull/75405#discussion_r271195049

**Comment by andrewsykim** [comment]
/close 

I think this has been addressed, thank you again @tghartland!
