### ISSUE TITLE
Investigate support for multiple route tables

### ISSUE THREAD

**Issue by aoxn** [kubernetes/cloud-provider#24]
### Problem Description
Many Cloud support multiple route tables under VPC. CCM Cloud Interface has poor support for multi-route tables. Consider ListRoutes() interface, It is confused for ListRoutes() to return which route tables`s entry.
For example, RouteTableA has route entry [1,2,3,4],   RouteTableB has route entry [2,3,4,5]
What result should ListRoutes() return?  Neither [1,2,3,4,5] nor [2,3,4] is good. For case [1,2,3,4,5] , CreateRoute() would not be called for entry [1] and [5] which is needed. 
For case [2,3,4] Delete() would not be called for the similar reason.

### Potential Solutions
1. Modify exist Interface, `ListRoutes(tableid string)`. Add interface AllRouteTables() []Tables

2. ListRoute() randomly return each route-table once a time. Reconcile would make sure the eventually consistency for route tables.

**Comment by andrewsykim** [comment]
@aoxn what's the use-case for multiple route tables?

**Comment by aoxn** [comment]
The background is that CCM goes wrong when user has multiple routetalbes under their VPC.  Because the default ccm behavior is to write the 0th route table which would not be the target(route table). 

Alibaba Cloud use a self defined controller extended cloudprovider interface to solve this issue for now. It might be better to solve it in cloudporivder interface level as other provider may face the same problems.

**Comment by andrewsykim** [comment]
ping @aoxn what's the status of this for v1.17?

**Comment by aoxn** [comment]
@andrewsykim  I am afraid a new Interface would be add in order to support multiple routetables
```
// Routes is an abstract, pluggable interface for advanced routing rules.
type Routes interface {
	// RouteTables get all available route tables.
	RouteTables(clusterName string) ([]string, error)
	// ListRoutes lists all managed routes that belong to the specified clusterName
	ListRoutes(clusterName string, table string) ([]*cloudprovider.Route, error)
	// CreateRoute creates the described managed route
	// route.Name will be ignored, although the cloud-provider may use nameHint
	// to create a more user-meaningful name.
	CreateRoute(clusterName string, nameHint string, table string, route *cloudprovider.Route) error
	// DeleteRoute deletes the specified managed route
	// Route should be as returned by ListRoutes
	DeleteRoute(clusterName string, table string, route *cloudprovider.Route) error
}

```
