### ISSUE TITLE
Move cmd/cloud-controller-manager and its controllers to k8s.io/cloud-provider (staging)

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#29]
Right now, out-of-tree providers end up vendoring a lot of `k8s.io/kubernetes` because they need to import `cmd/cloud-controller-manager`. `cmd/cloud-controller-manager` should be easier to consume, ideally living in it's own repository or moved to `k8s.io/cloud-provider`.

Similar to what we did for in-tree providers (`k8s.io/kubernetes/pkg/cloudprovider/providers`) we need to start pruning some of the internal dependencies for `cmd/cloud-controller-manager` as a starting point

**Comment by andrewsykim** [comment]
@timoreimann

**Comment by andrewsykim** [comment]
Agreed design for v1.16

**Comment by andrewsykim** [comment]
After some thought, I'm in favor of moving `cmd/cloud-controller-manager` to `k8s.io/cloud-provider/cmd/cloud-controller-manager`.

**Comment by cheftako** [comment]
I think its a good idea. We will need another extract to staging effort to make this work.
Look at https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/BUILD#L14, https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/apis/config/BUILD#L14 and https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/options/BUILD#L18 for an idea of what needs to be extracted.

**Comment by deitch** [comment]
Oh so happy to see this. Spent far too much time today because of this, and kindly helped by some go community people and of course @timoreimann.

**Comment by yastij** [comment]
@deitch - I'm filing the rest of the PRs before the 1.17 release, I expect the final move to happen in 1.18, this would leave a whole release for providers to migrate their imports.

@andrewsykim @cheftako @nckturner @craiglpeters et all does this timeline sound reasonable ?

**Comment by andrewsykim** [comment]
Sounds good to me, let's put this as p0 for v1.18

**Comment by nckturner** [comment]
Yup, 1.18 sounds like a reasonable timeline to me.

**Comment by yastij** [comment]
FYI @liggitt @dims

**Comment by onitake** [comment]
Related: Is there already an issue or a guide related to simplifying/streamlining options parsing?

We still use a IMHO pretty terrible way to parse options: https://github.com/apache/cloudstack-kubernetes-provider/blob/master/cmd/cloudstack-ccm/main.go#L45-L50
This was the only sensible way that I could find back when we forked, in part due to a lack of experience.

If not, I will gladly open a new issue.

**Comment by andrewsykim** [comment]
k8s.io/kubernetes/cmd/cloud-controller-manager -> k8s.io/cloud-provider/cmd/cloud-controller-manager
k8s.io/kubernetes/pkg/controllers/{cloud,service,route} -> k8s.io/cloud-provider/controllers

**Comment by andrewsykim** [comment]
ref https://github.com/kubernetes/kubernetes/issues/81172

**Comment by andrewsykim** [comment]
cc @cici37

**Comment by nilo19** [comment]
For clarity, all the inner deps of cmd/cloud-controller-manager:
```
k8s.io/kubernetes/cmd/cloud-controller-manager/app/apis/config
k8s.io/kubernetes/cmd/controller-manager/app
k8s.io/kubernetes/pkg/api/legacyscheme
k8s.io/kubernetes/pkg/cloudprovider/providers
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/controller/apis/config
k8s.io/kubernetes/pkg/controller/apis/config/v1alpha1
k8s.io/kubernetes/pkg/controller/cloud
k8s.io/kubernetes/pkg/controller/route
k8s.io/kubernetes/pkg/controller/service/config
k8s.io/kubernetes/pkg/controller/service/config/v1alpha1
k8s.io/kubernetes/pkg/controller/service
k8s.io/kubernetes/pkg/features
k8s.io/kubernetes/pkg/master/ports
k8s.io/kubernetes/pkg/util/configz
```

**Comment by deitch** [comment]
I am really glad to see this. Has documentation been updated? How do we update our downstream dependencies?

**Comment by cheftako** [comment]
Hi @deitch, I believe @cici37 has another PR #93764 which should make the CCM even easier to consume. I think it includes a clearer distinction between the sample code and a CCM library. We will make sure to add something to this releases notes on using it.

**Comment by deitch** [comment]
Thanks. I'm looking forward to it.

**Comment by andrewsykim** [comment]
Fwiw though, this is technically breaking change at the Go package-level, but IMO this brekaing change is worth-while to cut k/k from the dep graph.

**Comment by deitch** [comment]
I maintain the Equinix (formerly Packet) CCM, I am super happy to rebuild with this cleanup. Breaking changes for the win here :-)
