### ISSUE TITLE
Support of instance metadata service

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/cloud-provider#30]
Before CCM, kubelet supports getting Node information by cloud provider's instance metadata service. This includes:

•	NodeName
•	ProviderID
•	NodeAddresses
•	InstanceType
•	AvailabilityZone

Instance metadata service could help to reduce API throttling issues, and increase the nodes initialization duration. This is especially helpful for large clusters.

But with CCM, this is not possible anymore because the above functionality has been moved to cloud controller manager. We should add this back into Kubelet.

Since cloud providers are moving to external, we may need to add new plugins into Kubelet, e.g. via grpc.

Refer #14 (#14 is focused on node controller, while this one is focused on cloud API throttling).

@andrewsykim @justaugustus @craiglpeters  Any ideas on this?

**Comment by andrewsykim** [comment]
ref: https://github.com/kubernetes/cloud-provider/issues/15 https://github.com/kubernetes/cloud-provider/issues/14

**Comment by andrewsykim** [comment]
I think we should put this in high priority for v1.16. It's a common problem across multiple providers and is likely going to make the out-of-tree provider migration difficult

**Comment by andrewsykim** [comment]
I'm not sure if this will be feasible, but at the very least we should focus efforts in making controllers API quota sensitive before we invest efforts in something like this. We can make API quota sensitive controllers a high priority for v1.16 as a first step and go from there. What do you think?

**Comment by feiskyer** [comment]
> We can make API quota sensitive controllers a high priority for v1.16 as a first step and go from there. What do you think?

Yep, that may be the first step. Meanwhile, I'm thinking the solutions for such issues, so that CCM still has the same performance as KCM.

**Comment by andrewsykim** [comment]
> so that CCM still has the same performance as KCM.

The only controller that is different from KCM is cloud node controller, I think https://github.com/kubernetes/kubernetes/pull/75405 should help with this a lot

**Comment by feiskyer** [comment]
> I think kubernetes/kubernetes#75405 should help with this a lot

Yep, but still not enough. e.g. for cluster provision step, hundreds of nodes are initialized at the same time. kubernetes/kubernetes#75405 could reduce the errors in node controller, but the node initialization may be still slow because of API throttling.

With instance metadata, however, all nodes could init them without any API invoking, hence no API throttling would happen and nodes could be registered much faster.

**Comment by andrewsykim** [comment]
> Yep, but still not enough. e.g. for cluster provision step, hundreds of nodes are initialized at the same time. kubernetes/kubernetes#75405 could reduce the errors in node controller, but the node initialization may be still slow because of API throttling.

Agreed that we should improve this, but we should be mindful that this is a one time cost when the cluster is being created and we should optimize for that and nothing more.

**Comment by andrewsykim** [comment]
@feiskyer are you able to validate if https://github.com/kubernetes/kubernetes/pull/75405 is helping with this problem for Azure?

**Comment by feiskyer** [comment]
@andrewsykim Yep, of course. Would do it.

**Comment by andrewsykim** [comment]
@feiskyer any updates on this one?

**Comment by feiskyer** [comment]
@andrewsykim Based on Azure API throttles, this is still a hard requirement for Azure cloud provider. I'm planning to draft a proposal for this during v1.16.

/milestone v1.16
/assign

**Comment by feiskyer** [comment]
@andrewsykim I'm preparing the proposal [here](https://docs.google.com/document/d/1ihMwAuTRKWBhqvExh09E51NA-u1EJw9Hj1w9kAjFF3I/edit). Would you like having a look before I send it out as KEP?

**Comment by feiskyer** [comment]
Opened the KEP here: https://github.com/kubernetes/enhancements/pull/1158.
