### ISSUE TITLE
Handle volume scheduling when nodes are shutdown 

### ISSUE THREAD

**Issue by yastij** [kubernetes/cloud-provider#31]
Currently if a node gets shutdown, pods using volumes don't get rescheduled, Since we don't know if the volumes are still being used.

Two solutions:

- Create a flow that has an interlock between node lifecycle controller, taintManager, PodGC, attach_detach_controller and kubelet, one of the drawbacks of this solution is that we need to tie taint removal to finishing the eviction (more specifically to finishing volume detach)

- Rely on nodeReadiness Gate and let cloud provider implement a node condition shutdown, act upon it to detach the volume and remove it, one of the drawbacks of relying on condition is that we cannot tolerate them.

cc'ing folks involved for thoughts @smarterclayton @liggitt @andrewsykim @jingxu97 and @yujuhong 

/assign

**Comment by andrewsykim** [comment]
KEP https://github.com/kubernetes/enhancements/pull/1116

**Comment by andrewsykim** [comment]
/close

This probably belongs in SIG node going forward
