### ISSUE TITLE
Allow discovering node changes for load-balancer targets more frequently

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/cloud-provider#38]
The [nodeSyncPeriod in service_controller.go](https://github.com/kubernetes/kubernetes/blob/57eef320414f46165fc775472a0dc402bcd39311/pkg/controller/service/service_controller.go#L55) defines the interval at which changes in nodes (additions, removals) will be discovered for the purpose of updating a load-balancer's target node set. It is currently hard-coded to 100 seconds and defined as a constant. This means that an update in a node pool can take up to 100 seconds to be reflected in a cloud load-balancer.

I'd like to explore opportunities to reduce latency at which node changes can propagate to load-balancers.

**Comment by timoreimann** [comment]
Likely the easiest approach would be to expose the interval through a flag that could be set based on a cloud's / customer's preferences.

A different approach could be to extend the existing resource event handler in order to watch over nodes as they come and go. This would presumably minimize latency at the trade-off of increased complexity and load-balancer updates triggered for each individual node. The latter in particular may lead to a high number of cloud API requests when many nodes are at play.

**Comment by andrewsykim** [comment]
I feel a good first step would be adding node watchers to update [knownHosts](https://github.com/kubernetes/kubernetes/blob/57eef320414f46165fc775472a0dc402bcd39311/pkg/controller/service/service_controller.go#L86) instantly, that doesn't trigger an LB update, but it ensures that the next service update always has the latest node objects

**Comment by timoreimann** [comment]
@andrewsykim can we reopen?

**Comment by andrewsykim** [comment]
https://github.com/kubernetes/kubernetes/pull/81185 will be included in v1.19

**Comment by sterchelen** [comment]
Can we re-open the issue please? 
We are still in the same situation as before, 100 second hard-coded https://github.com/kubernetes/cloud-provider/blob/016d675f2dd271246e45aa8a1e5b17fd1909539c/controllers/service/controller.go#L51
