### ISSUE TITLE
Should limit the LoadBalancing rule's resource name length less than 80 characters long

### ISSUE THREAD

**Issue by chengliangli0918** [kubernetes/cloud-provider#41]
When cloud provider creates LB, the LB rule's resource name is following the following pattern a7600d690dbdf11e9955da6e322bb002-[subnet name]-TCP-20201. If the subnet name is long, the rule's resource name is more than 80 characters long and the Azure NRP files the LB creation with following error: Cloud Provider should limit the LoadBalancing rule's resource name length less than 80 characters long.

E0920 15:42:22.281115       1 azure_backoff.go:565] processHTTPRetryResponse: backoff failure, will retry, err=network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceName" Message="Resource  name a3c276d5bdbbd11e9a0ab065512a4bb2-**ms-72164-rice-vmn-eastus2-n-services-subnet**-TCP-20201 is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]

**Comment by feiskyer** [comment]
Dup of #86275, which has been fixed by #86276.

/kind bug
/remove-lifecycle stale
/area provider/azure
