### ISSUE TITLE
--cloud-provider cannot be empty

### ISSUE THREAD

**Issue by paullaffitte** [kubernetes/cloud-provider#45]
Using one of the sample main results in an error `--cloud-provider cannot be empty` with an exit status 1. Specifying this flag doesn't change anything.

**Comment by falzm** [comment]
Any news on this issue @cici37 @andrewsykim?

**Comment by cici37** [comment]
The fix is merged in upstream (https://github.com/kubernetes/kubernetes/pull/98210)
There are some workaround samples in this issue: https://github.com/kubernetes/cloud-provider/issues/44
Without the fix, this issue could be addressed by reconstruct cobra command in cloud provider repo.

**Comment by cici37** [comment]
Update: The fix was cherry picked to 1.20 release: https://github.com/kubernetes/kubernetes/pull/100722
