### ISSUE TITLE
Backoff not respected due to resync

### ISSUE THREAD

**Issue by sfiera** [kubernetes/cloud-provider#46]
I’ve been investigating an issue in our custom controller-manager where it appears that the backoff settings from service.Controller ([exponential](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L131) from [5s to 5m](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L56-L57)) weren’t respected. Our backend was timing out, and the controller retried soon after (within 30s), which compounded the issue.

I believe that this is due to the [resync interval](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L49):

Down in [processNextWorkItem()](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L243-L257), at the end of a failed attempt, the controller will:
1. Schedule the service to be re-enqueued after backoff. (`s.queue.AddRateLimited(key)`)
2. Remove the service from the queue. (`s.queue.Done(key)`)
3. Wait for the backoff interval to elapse.
4. Re-enqueue the service.

However, if a resync happens, then service.Controller [re-enqueues](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L136-L143) it [without backoff](https://github.com/kubernetes/cloud-provider/blob/e98fefa45a6c0bc0398c647678e5e486a5da3662/controllers/service/controller.go#L202). Because of the way that DelayingQueue works, an item is not (as far as I can tell) considered to be queued during (3), so the service key is not deduplicated as it would be for consecutive calls to Add().

The end result is that, despite `maxRetryDelay` of 5 minutes, service.Controller will never wait more than 30s before its next attempt to sync services.

There is a separate, related issue in [kubernetes/client-go#131](https://github.com/kubernetes/client-go/issues/131). It’s sort of the reverse. Here, I think that the call to AddRateLimited() should cancel a future call to Add(). There, the author wants a call to Add() to cancel a past call to AddRateLimited().

**Comment by sfiera** [comment]
I should add: resync removes loadbalancers, but does not add them. So, the backoff settings are ignored when deleting loadbalancers, but respected when adding or updating them.

**Comment by timoreimann** [comment]
/remove-lifecycle rotten

Thanks for reporting. This needs to be triaged.
