### ISSUE TITLE
Allow NotReady nodes to take part in load balancing

### ISSUE THREAD

**Issue by baranov1ch** [kubernetes/cloud-provider#47]
[This code](https://github.com/kubernetes/cloud-provider/blob/5a236942a3ca6f0454bfcb979cc31207af4894b2/controllers/service/controller.go#L679) says that only Ready nodes will be used when configuring cloud load balancers for a service. This means that k8s control-plane problems may lead to workload outages. If for any reason k8s master will see nodes as 'not ready' - connectivity problems between master and nodes, kubelet network issues like [this one](https://github.com/kubernetes/kubernetes/issues/87615), cloud firewall misconfiguration - anything, such nodes will be removed from the load balancing. It seems to me, that if such problems occur in the cluster, more stable behaviour would be to keep load balancer targets just as they are, and let the load balancer to rely on kube-proxy healthchecks (default or service-specific) to determine, which nodes are ready to serve traffic.

**Comment by cheftako** [comment]
/sig networking
While under the cloud-provider staging directory, service controller is primarily owned by networking. You may also be better of filing this in the main K/K repo than in K/cloud-provider.

**Comment by cheftako** [comment]
OK can't label sig-networking, you definitely want to file this issue in K/K rather than K/cloud-provider.
