### ISSUE TITLE
Cloud controllers should not reuse names and cluster roles of KCM controllers

### ISSUE THREAD

**Issue by nckturner** [kubernetes/cloud-provider#48]
Currently, a cluster operator can run their external cloud controller manager with `--use-service-account-credentials` enabled or disabled.  If the flag is enabled, then each controller (control loop) gets its own service account token, using a hardcoded name ([like "node-controller"](https://github.com/kubernetes/cloud-provider/blob/5a236942a3ca6f0454bfcb979cc31207af4894b2/app/core.go#L47)).  This is the name used for the service account, so it also needs to be present in the role binding for that controller.  Currently, cloud providers may not have taken the time to recreate each controllers role and rolebinding separately from the upstream roles, and are (at least in AWS's case) piggybacking on the upstream roles.  We want to move to custom cluster roles and role bindings, and it might make sense to deprecate the upstream roles eventually to reduce confusion.  

I propose we differentiate the names of the controllers once they move to the external CCM, so that they can be differentiated in audit logs and from similar loops in the KCM.  (e.g., the "node-controller" currently refers to three separate controllers, the cloud-node, the cloud-node-lifecycle, and the in-tree node-lifecycle (and maybe node-ipam too :D).    

If we decided to do this, we could allow these names to be plumbed in from each cloud provider repository, so they can be cloud provider specific, or we could all agree on something like cloud-*-controller.

**Comment by andrewsykim** [comment]
I agree with the premise, but concerned about breaking compatibility

**Comment by nckturner** [comment]
> I agree with the premise, but concerned about breaking compatibility

Definitely, but regardless of whether the upstream roles are deprecated, we could allow cloud providers to both use the k8s.io/cloud-provider libraries and use custom names and roles, right?

**Comment by cheftako** [comment]
What about extending https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/app/controllermanager.go#L360?
Right now its just the controller name and initializer. However we could extend that to include the desired SA.
We already allow the cloud providers to over-ride this, so it seems a natural way to let them control the change.

**Comment by nckturner** [comment]
Yeah, that seems like a good place to do it.
