### ISSUE TITLE
ccm version information not displayed correctly on using latest code

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider#49]
On reusing `NewCloudControllerManagerCommand` defined here https://github.com/kubernetes/cloud-provider/blob/master/app/controllermanager.go#L69 , version information is not displayed correctly.
Ref: https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/openstack-cloud-controller-manager/main.go#L55

        $ ./cloud-controller-manager --version 
        Kubernetes v0.0.0-master+$Format:%H$

**Comment by nckturner** [comment]
This worked for me with the AWS CCM: https://github.com/kubernetes/cloud-provider-aws/pull/317

**Comment by olemarkus** [comment]
/remove-lifecycle rotten

Works for tagged releases, but still broken for pre-releases:
```
panic: version string "v20220328-helm-chart-aws-cloud-controller-manager-0.0.6-25-g3b97652" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"
```
