### ISSUE TITLE
Improving AWS Integration docs

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#5]
AWS integration docs should be updated as per https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/0019-cloud-provider-documentation.md.

**Comment by andrewsykim** [comment]
cc @jaypipes

**Comment by jaypipes** [comment]
Note the link should be https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180731-cloud-provider-docs.md

**Comment by andrewsykim** [comment]
@nckturner any updates on this?

**Comment by elmiko** [comment]
discussing this at the sig cloud provider meeting today, we think this should be closed out and picked up in the cloud-provider-aws repository.

/close
