### ISSUE TITLE
Improving Azure Integration Docs

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#6]
Azure integration docs should be updated as per https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/0019-cloud-provider-documentation.md

**Comment by feiskyer** [comment]
Would address this later

/assign

**Comment by feiskyer** [comment]
Added in https://github.com/kubernetes/enhancements/pull/1048

/close

**Comment by andrewsykim** [comment]
@feiskyer I see the KEP merged but have the docs been written?

**Comment by feiskyer** [comment]
We have added some docs on cloud-provider-azure, but it's not fully organized as the KEP's structure.

/open
/area provider/azure
