### ISSUE TITLE
[Feature discussion] Loadbalancer support to route traffic directly to Pods instead of NodePort.

### ISSUE THREAD

**Issue by chestack** [kubernetes/cloud-provider#60]
Loadbalancer is able to route traffic directly to Pods instead of NodePort for some cloud platforms with cni supported.
such as:
- GKE container-native LB: https://cloud.google.com/kubernetes-engine/docs/concepts/container-native-load-balancing
- EKS NLB IP mode: https://github.com/aws/containers-roadmap/issues/981 

So should we add a new loop like _syncEndpoint_ into loadbalancer controller to update loadbalacer with pods ips

```
func (s *Controller) Run(ctx context.Context, workers int) {
	for i := 0; i < workers; i++ {
		go wait.UntilWithContext(ctx, s.worker, time.Second)
	}

	go s.nodeSyncLoop(ctx, workers)

        // Add syncEndpoint code here
}
```

**Comment by olemarkus** [comment]
AWS at least seems pretty clear they will deprecate the service controller for their own AWS Load Balancer Controller.
