### ISSUE TITLE
Many CCM in one cluster.

### ISSUE THREAD

**Issue by sergelogvinov** [kubernetes/cloud-provider#63]
Hello. I'd like to launch two CCM in one k8s cluster (one control plane)

Currently, CCM is trying to manage all nodes in the cluster, even if they have different ProviderName. 
And one CCM can delete a node which uninitialized because it does not find the node in the cloud provider and does not have ProviderID yet.

Can we skip managing the foreign nodes? And add delete delay for uninitialized nodes?

a few changes here https://github.com/sergelogvinov/cloud-provider/commit/8468b74886fb0815fc75c294ae26c3629b0e8934

So, what do you think, is it possible to solve the problem like this?

**Comment by cheftako** [comment]
Having multiple copies of the same controller operating simultaneously is asking for race conditions. Currently we prevent this using controller manager level leader election. I am assuming that you have already given one of the two CCMs an alternate leader election name to circumvent the leader election protection. If you want to go that route I would suggest using the controllers flag (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/controller-manager/options/generic.go#L65) to control the controllers in each CCM to ensure that each controller is only running in one of the two CCMs.

**Comment by james-callahan** [comment]
I have this same question: how has anyone implemented a multi-cloud kubernetes cluster without this?
