### ISSUE TITLE
Meaning of HasClusterID() ?

### ISSUE THREAD

**Issue by guettli** [kubernetes/cloud-provider#64]
I don't understand HasClusterID.

I don't see any usage except of base_main.go, but this is not production code:

```
cloud-provider on  master via 🐹 v1.19.4 
❯ rg HasClusterID
fake/fake.go:149:4:// HasClusterID returns true if the cluster has a clusterID
fake/fake.go:150:17:func (f *Cloud) HasClusterID() bool {
sample/basic_main.go:88:12:     if !cloud.HasClusterID() {
cloud.go:67:5:  // HasClusterID returns true if a ClusterID is required and set
cloud.go:68:2:  HasClusterID() bool
```

If it is not relevant, than why not remove the part in base_main.go and update the docstring of the the method?

**Comment by guettli** [comment]
Related issue: https://github.com/kubernetes/cloud-provider/issues/12

**Comment by andrewsykim** [comment]
Generally it is used for including a unique tag to resources owned by a cluster. Usually for resource tracking purposes

**Comment by guettli** [comment]
@andrewsykim I could not find a place where HasClusterID() gets used. Could you please point me to a place where the return value of this method makes a difference.

**Comment by elmiko** [comment]
i've been talking on slack with @guettli about this issue, i think it is worth investigating to determine how we should proceed in to the future with this interface. i think it would be nice to determine how the cluster id is intended to be used, and then document more thoroughly around how providers want to implement. alternatively, if we determine that it will not be used, then we can start investigating its deprecation.

i'd like to bring this issue up at the next cloud provider meeting before re-opening.
