### ISSUE TITLE
Node deletion via CCM

### ISSUE THREAD

**Issue by RealHarshThakur** [kubernetes/cloud-provider#66]
When a user performs a "kubectl delete node [node]" , CCM could delete the node from the underlying infra. As a cloud provider, we would like that to be an option in our CCM deployments. While I understand, this may not be the default choice for all providers out there,  there should be a knob to indicate what "kubectl delete node [nodename]" should mean based on CCM deployments. 

Maybe something as part of this interface? 
https://github.com/kubernetes/cloud-provider/blob/322c087411fe027de06291c6ad974ed7bcbf2eea/cloud.go#L199

**Comment by elmiko** [comment]
i commented on the [slack thread about this topic](https://kubernetes.slack.com/archives/C718BPBQ8/p1684140788709869) , i have a feeling that a change like this should be discussed with SIG cluster-lifecycle and perhaps SIG architecture as well. my reasoning here is that this is going to be a larger structural change to kubernetes in the way users have expected it to behave, and i think there will need to be some consensus from the community around the new behavior. (probably a KEP involved at some point as well)
