### ISSUE TITLE
RFE: Ability to return arbitrary node labels from cloud provider

### ISSUE THREAD

**Issue by mdbooth** [kubernetes/cloud-provider#67]
My specific use case here is adding a node label representing the specific hypervisor a node is on. This is an extremely common request on OpenStack, where not all deployments use availability zones. Even in deployments which use availability zones, the ability to schedule a workload to survive node maintenance within a single AZ is still a common request.

There is no well-known label representing a node's hypervisor. In fact, to the best of my knowledge this has been specifically discussed and rejected in the past. Consequently I would likely implement this as an OpenStack-specific node label.

I could write a new controller for OpenStack, but the existing node controller very nearly does this already. We could add a new field to InstanceMetadata:

```go
type InstanceMetadata struct {
  ...
  // Labels is a set of additional labels to apply to the created node
  Labels map[string]string `json:"labels,omitempty"
  ...
}
```

This should have no impact on cloud providers which do not implement it.

I propose this rather than a new `Hypervisor` field as I suspect it may be generally useful for a number of use cases over time in addition to this one.

**Comment by matofeder** [comment]
+1
