### ISSUE TITLE
Implementing a cloud-controller-manager without golang (i.e. as an REST API server or in another language

### ISSUE THREAD

**Issue by MasterMann** [kubernetes/cloud-provider#69]
This is more of a question, not an issue. I'm looking for ways to implement a cloud controller manager for my cloud provider, but without using golang, since I'm building other parts of the infrastructure in other languages (i.e. C#).  
Is it possible to expose CCM as a REST API server for other k8s components, or using the go language and cloud-provider package is a strict dependency?  

Thanks.

**Comment by fischerman** [comment]
CCM is effectively just a set of controllers. I.e. no Kubernetes component calls CCM, instead CCM reacts. To share the logic of those controllers, they call an interfaces in Go that can be implemented by each cloud provider. If you don't want to use Go you can't use that approach. However, technically, you could implement the controllers from scratch in any language.
