### ISSUE TITLE
Prevent Empty ProviderID in CloudNodeLifecycleController

### ISSUE THREAD

**Issue by mgrote** [kubernetes/cloud-provider#70]
**What happened**:

When creating new nodes the existence of the property `node.Spec.ProviderID` is not sure. Due to race conditions, the `ProviderID` may not yet be set by the CloudProviderImplemtation, but the node is already evaluated by CCM.                                                                                                                                                        
Currently this results in an empty ProviderID provided to the CloudProviderImplemtation by the CloudLifecycleControlle when calling `shutdownInCloudProvider`. If the implementation is not prepared to work with an empty ProviderID, it will cause an error in the implementation.

**What you expected to happen**:

The `node.Spec.ProviderID` should be set when the controller is able to fetch the correct ProviderID from the provider implementation.

The CloudLifecycleController itself is prepared to work with an empty ProviderID, but does not store the evaluated ProviderID in the node reference used later on (see [ensureNodeExistsByProviderID](https://github.com/kubernetes/cloud-provider/blob/a5b00cde736d87324a85853929b83eddd855f49f/controllers/nodelifecycle/node_lifecycle_controller.go#L231C2-L245C3)). 

A simple assignment of the evaluated ProviderID will fix the issue. 

**How to reproduce it**:

This is a race condition and cannot be reproduced easily.
It occurs randomly and can be kind of reproduced with clusters that have more than 10 worker nodes.

**Anything else we need to know?**:

We fixed this already in our fork succesfully.

<sup>Michael Grote [michael.grote@mercedes-benz.com](mailto:tobias.giese@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by tobiasgiese** [comment]
/close

dup of https://github.com/kubernetes/kubernetes/issues/120617
