### ISSUE TITLE
CCM may not work when Instances or InstancesV2 isn't implemented

### ISSUE THREAD

**Issue by xagent003** [kubernetes/cloud-provider#72]
Usecase: We want to use the CCM for LBaaS. We don't have and/or don't want to implement a cloud compute API. The LBaaS functionality just relies on the Service and Node resources.

So kubelet taints the nodes when they come up, until the CCM does it's initialization.

However the CCM expects either Instances or InstancesV2 to be implemented to fetch some metadata. If neither are implemented or the metadata returned is nil, it returns an error here: https://github.com/kubernetes/cloud-provider/blob/b60a8ce912a9b753d4561d127bdd454222f90284/controllers/node/node_controller.go#L605

syncNode returns prematurely here if metadata is nil or there is an error: https://github.com/kubernetes/cloud-provider/blob/b60a8ce912a9b753d4561d127bdd454222f90284/controllers/node/node_controller.go#L434

As a result, it never gets here to remove the taint from the node and update the Node: https://github.com/kubernetes/cloud-provider/blob/b60a8ce912a9b753d4561d127bdd454222f90284/controllers/node/node_controller.go#L449

Therefore the node remains tainted and unuseable. But if you look at the code, it seems like the instances metadata can be empty - just not nil. I think syncNode should work if Instances is not implemented - is there any absolute requirement on instances/instance metadata when we want to leverage CCM just for loadbalancers?

**Comment by elmiko** [comment]
thank you for reporting this @xagent003 , it is a good question.

this repository is mirrored from the staging location in the kubernetes/kubernetes repository, would you mind opening this issue there? (apologies for the confusion)

https://github.com/kubernetes/kubernetes/issues

**Comment by elmiko** [comment]
i think we need to get this into k/k, if i have some time next week i will post it there.
