### ISSUE TITLE
Improving OpenStack Integration Docs

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider#8]
OpenStack integration docs should be updated as per https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180731-cloud-provider-docs.md

**Comment by andrewsykim** [comment]
@hogepodge should this still be p0 for v1.16?

**Comment by hogepodge** [comment]
Yes.

**Comment by andrewsykim** [comment]
cc @diablo_rojo

**Comment by adisky** [comment]
@andrewsykim it is returning `404` https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/0019-cloud-provider-documentation.md
could you help me where to update the docs?? we maintain docs here https://github.com/kubernetes/cloud-provider-openstack/tree/master/docs, is it needs to be updated in k/website?

**Comment by adisky** [comment]
got it 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20180731-cloud-provider-docs.md

**Comment by elmiko** [comment]
discussing this at the sig cloud provider meeting today, we think this should be closed out and picked up in the cloud-provider-openstack repository.

/close
